# Generated by Django 5.0.1 on 2024-01-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0002_emailverificationresult_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerificationResult',
            new_name='EmailVerification',
        ),
    ]
