# Generated by Django 5.0.1 on 2024-01-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0003_rename_emailverificationresult_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='status',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
